# Generated by Django 5.1.6 on 2025-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='address',
            field=models.CharField(default='Trichy to Tanjore', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='contact',
            field=models.CharField(default='+91 98765 43210', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='destination',
            field=models.CharField(default='Tanjore', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='status',
            field=models.CharField(default='In Transit', max_length=255),
        ),
    ]
